name: Build Shiny Docker Image and Deploy to Heroku

# Set here what events should trigger the action
on:
  push:
    branches:
#      - main
#      - master
      - folder

# jobs can be added, deploy depends on commit message

jobs:
  app1:
    runs-on: ubuntu-latest
    # commit message needs to contain 'deploy app' to trigger job
#    if: "contains(github.event.head_commit.message, 'deploy app1')"
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      # Edit app name and dir as needed, email and api key should apply to
      # multiple apps from the same repo
#      - name: Build and push Docker to Heroku
#        env:
#          HEROKU_APP_NAME: shiny-app-folder
#          DOCKERFILE_DIRECTORY: "project"
#          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
#          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#          DOCKERFILE_NAME: "Dockerfile"
#          DOCKER_OPTIONS: "--no-cache"
#        run: |
#          # change dir
#          cd ${DOCKERFILE_DIRECTORY}
#          # Heroku Docker registry login
#          echo ${HEROKU_API_KEY} | docker login --username=${HEROKU_EMAIL} registry.heroku.com --password-stdin
#          # build image
#          docker build --file ${DOCKERFILE_NAME} ${DOCKER_OPTIONS} --tag registry.heroku.com/${HEROKU_APP_NAME}/web .
#          # push
#          heroku container:push web --app ${HEROKU_APP_NAME}
#          # release
#          heroku container:release web --app ${HEROKU_APP_NAME}

      ## set appdir and app name to the job specific one
      - name: Build and push Docker to Heroku
        uses: akhileshns/heroku-deploy@v3.11.10
        with:
          appdir: project
          heroku_app_name: shiny-app-folder
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
